project_prod:
  target: dev
  outputs:

    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID_DEV') }}"
      dataset: "{{ env_var('GCP_DATASET_DEV') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_SA_DEV') }}"

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID_PROD') }}"
      dataset: "{{ env_var('GCP_DATASET_PROD') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_SA_PROD') }}"